### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/ccd-web#59] opened 2017-05-20 13:49 UTC
a ccd user tried causal web and got this error message. Any idea what's up and how we can fix it?

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/pitt/dbmi/causal/cmd/CausalCmdApplication : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by marksilvis** [comment] 2017-05-20 14:34
It looks like possibly a Java version mismatch. [This Stackoverflow answer](http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0#answers) says it can be caused when running with a lower version of Java than what it was compiled in.

**Comment by harryhoch** [comment] 2017-05-20 14:49
ok. How do we get this fixed. @kvb2univpitt, is this a question of a rebuild, or do we need to change the JVM on the vm?

**Comment by marksilvis** [comment] 2017-05-20 14:56
If this is the cause then it's likely that the application was built with Java 8, and the JVM version on the vm needs to be updated. I can confirm the JVM version if you tell me which vm was used.

**Comment by harryhoch** [comment] 2017-05-20 14:59
Mark, I think @kvb2univpitt might know, but I don't. I think we need to (a) fix this problem, and (B) institute a means of ensuring that it doesn't happen again in the future..

**Comment by kvb2univpitt** [comment] 2017-05-23 21:30
Based on the error message, this is a causal-cmd problem and not causal-web.  Do we know what version of causal-cmd the user was using?

**Comment by harryhoch** [comment] 2017-05-24 10:55
No, they were running causal web.  this is the message they sent me:

"
I uploaded a file to the website. This file contains 200 records of workflow observations, each observation has 11 columns of time allocation (%) on certain task themes (A-K), with the last column indicating the level of switch between tasks. While the website was intuitive and easy to use, I got an error message as attached. Do you have any idea how to resolve this?"

**Comment by harryhoch** [comment] 2017-05-24 12:06
@kvb2univpitt , I have just confirmed - I tried to run FGESc  on the Retention data and got precisely the error above.

Please take a look - try it yourself. I'm guessing this has not been working for anyone for several days.

**Comment by kvb2univpitt** [comment] 2017-05-24 12:26
Can you please send me the what version of causal-web you downloaded?  What version of causal-cmd you downloaded?  What version is your Java?  I'll try to repeat you you did.

**Comment by harryhoch** [comment] 2017-05-24 12:27
@kvb2univpitt, this is all with the causal-web that is live from the site. https://ccd2.vm.bridges.psc.edu/ccd/home

**Comment by kvb2univpitt** [comment] 2017-05-24 12:34
Ok. I see.  It might be Bridges.  I'll figure it out and keep you posted.

**Comment by harryhoch** [comment] 2017-05-24 12:35
thanks

**Comment by kvb2univpitt** [comment] 2017-05-24 18:18
The problem was with the slurm script.  It loaded Java 7 instead of Java 8.  @marksilvis was right; it was the Java version problem.  It is now fixed.  I am going to close this issue.

**Closed as completed by kvb2univpitt** 2017-05-24 18:18 UTC
